name: sass_calibration
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - attrs=21.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bottleneck=1.3.2=py38heb32a55_1
  - brotlipy=0.7.0=py38h27cfd23_1003
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py38h06a4308_0
  - cffi=1.14.6=py38h400218f_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=3.4.7=py38hd23ed53_0
  - flake8=3.9.2=pyhd3eb1b0_0
  - idna=3.2=pyhd3eb1b0_0
  - importlib-metadata=3.10.0=py38h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - mccabe=0.6.1=py38_1
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.2=py38h51133e4_0
  - more-itertools=8.8.0=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - numexpr=2.7.3=py38h22e1b3c_1
  - numpy=1.20.3=py38hf144106_0
  - numpy-base=1.20.3=py38h74d4b33_0
  - openssl=1.1.1k=h27cfd23_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandas=1.3.2=py38h8c16a72_0
  - pip=21.0.1=py38h06a4308_0
  - pluggy=0.13.1=py38h06a4308_0
  - py=1.10.0=pyhd3eb1b0_0
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pycparser=2.20=py_2
  - pyflakes=2.3.1=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h06a4308_0
  - pytest=6.2.4=py38h06a4308_2
  - pytest-flake8=1.0.7=pyhd3eb1b0_0
  - python=3.8.11=h12debd9_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - readline=8.1=h27cfd23_0
  - requests=2.26.0=pyhd3eb1b0_0
  - responses=0.13.3=pyhd3eb1b0_0
  - setuptools=52.0.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.2=pyhd3eb1b0_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wheel=0.37.0=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
prefix: /home/liz/anaconda3/envs/sass_calibration

