name: sass_env
channels:
  - conda-forge
  - defaults
dependencies:
  - pytest
  - pytest-benchmark
  - ipykernel
  - ipdb
  - isort
  - pip
  - pip:
    - flake8-per-file-ignores
    - flake8==3.8.4
    - flake8-docstrings
    - flake8-print
    - coverage